name: Deploy Frontend to S3 and CloudFront

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/deploy-frontend.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Create production .env file
        run: |
          echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" >> .env.production
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
        working-directory: ./client

      - name: Build Vite app
        run: npm run build
        working-directory: ./client

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.FRONTEND_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync built files to S3 bucket
        run: aws s3 sync ./dist/ s3://${{ vars.S3_BUCKET_NAME }} --delete
        working-directory: ./client

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/index.html"
